# Generated by Django 3.1.14 on 2025-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250614_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avatar_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Avatar 1'), (2, 'Avatar 2'), (3, 'Avatar 3')], default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Avatar 1'), (2, 'Avatar 2'), (3, 'Avatar 3')], default=1),
        ),
    ]
