# Generated by Django 3.1.14 on 2025-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250616_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar_index',
            field=models.CharField(choices=[('1', 'Avatar 1'), ('2', 'Avatar 2'), ('3', 'Avatar 3'), ('4', 'Avatar 4'), ('5', 'Avatar 5'), ('6', 'Avatar 6'), ('7', 'Avatar 7'), ('8', 'Avatar 8'), ('9', 'Avatar 9'), ('A', 'Avatar A'), ('B', 'Avatar B'), ('C', 'Avatar C'), ('D', 'Avatar D'), ('E', 'Avatar E'), ('F', 'Avatar F'), ('G', 'Avatar G'), ('H', 'Avatar H'), ('I', 'Avatar I'), ('J', 'Avatar J'), ('K', 'Avatar K')], default='1', max_length=2),
        ),
    ]
