# Generated by Django 3.1.14 on 2025-06-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20250615_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='date_requested',
            new_name='requested_at',
        ),
    ]
