# Generated by Django 3.1.14 on 2025-06-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20250616_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
